spring:
  application:
    name: hexagonal-architecture-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
server:
  port: 8081
  servlet:
    context-path: /hex/arch/



